networks:
  default:
    driver: bridge
    name: roboshop
    external: true # if network is already created manually
services:
  mongodb:
    image: bajipathan/mongodb:v1
    container_name: mongodb
  catalogue:
    image: bajipathan/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: redis:7.0
    container_name: redis
  user:
    image: bajipathan/user:v1
    container_name: user
    depends_on:
    - redis
    - mongodb
  cart:
    image: bajipathan/cart:v1
    container_name: cart
    depends_on:
    - catalogue
    - redis
  mysql:
    image: bajipathan/mysql:v1
    container_name: mysql
  shipping:
    image: bajipathan/shipping:v1
    container_name: shipping
    depends_on:
    - mysql
    - cart
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
